Repository Alphasians/AinaBot, pull requests merged in 2021-10, with the labels that each got.

#25 feat: invite command
  src/commands/misc/invite.js
  src/index.js
Labels: enhancement, first-timers, Hacktoberfest, hacktoberfest-accepted

#26 feat: level up command
  src/index.js
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#28 Cleaning the code and updating the Readme!
  Procfile
  readme.md
Labels: first-timers, Hacktoberfest, hacktoberfest-accepted
